# Generated by Django 4.2.7 on 2024-05-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFollowHistory',
            fields=[
                ('instagram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('follow_id', models.CharField(max_length=50)),
                ('parent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_follow_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountPool',
            fields=[
                ('follow_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_pool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceMaster',
            fields=[
                ('device_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('instagram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('preparation_flg', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('max_follow_count', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('request_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('file_name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('parent_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(blank=True, null=True)),
                ('update_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parent_account',
                'managed': False,
            },
        ),
    ]
